Better athena script

diff --git a/deploy/bin/athena b/deploy/bin/athena
--- a/deploy/bin/athena
+++ b/deploy/bin/athena
@@ -1,14 +1,18 @@
 #!/usr/bin/env bash
 set -eou pipefail
 
-get_status() {
+get_state() {
   local query_id="$1"
 
-  aws athena \
+  local status="$(aws athena \
     --region us-east-1 \
     get-query-execution \
     --query-execution-id "$query_id" | \
-    jq '.QueryExecution.Status.State'
+    jq '.QueryExecution.Status')"
+
+  local state="$(echo "$status" | jq -r '.State')"
+
+  echo "$state"
 }
 
 get_query () {
@@ -35,16 +39,26 @@ wait_til_finished() {
   local number_of_tries=5
 
   while [[ $status != done ]]; do
-    set +e
-    get_status "$query_id" | grep "SUCCEEDED" >/dev/null
-    if [[ $? -eq 0 ]]; then
-      status="done"
-      get_query "$query_id"
-    else
-      sleep 3
-      ((number_of_tries = number_of_tries -1))
-    fi
-    set -e
+    local state="$(get_state "$query_id")"
+
+    case "$state" in
+       FAILED | CANCELLED )
+        aws athena \
+          --region us-east-1 \
+          get-query-execution \
+          --query-execution-id "$query_id" | \
+          jq '.QueryExecution.Status.StateChangeReason' >&2
+
+        echo 'Athena query failed.' >&2 && exit 1 ;;
+      SUCCEEDED )
+        status="done"
+        get_query "$query_id" ;;
+      RUNNING | SUBMITTED )
+        sleep 3
+        ((number_of_tries = number_of_tries - 1)) ;;
+      * )
+        echo "Athena query state is unknown..: $state ... go tell John" >&2 && exit 1 ;;
+    esac
   done
 }
 
